name: Testing

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
